---
version: "3.7"
services:

  tor:
    image: goldy/tor-hidden-service
    container_name: oniontree_tor
    links:
    - oniontree
    depends_on:
    - oniontree
    networks:
    - onionltd
    # volumes:
    #- ./tor_keys:/var/lib/tor/hidden_service/
    environment:
      # PROXY_MAP: 8081:8081 # first port is exposed port and the second one is service internal port.
      # Set mapping ports
      SERVICE_TOR_SERVICE_HOSTS: 80:oniontree:9000
      # Set private key
      SERVICE_TOR_SERVICE_KEY: |
        -----BEGIN RSA PRIVATE KEY-----
        MIICXQIBAAKBgQDAvxO/JGtQqqvSBdxvH1ifxNmS6EbTe/ptSTYLshyu0RNcG32d
        f9KGHP3iOvoPQ1JYjvZlOaU1wOFW64oAiZjZhH8M6pQ+9uIz5v3KEe7HXWL052t0
        oZzXKGH7JM0v8h29Eng42i52/P0tnK5l8lEdc/zjjfP5efMG8+dNEJNrDwIDAQAB
        AoGADoUWbrrGntAMm4i3f2OEIJ0Kqud2lm3rgpoWSTFEueKkK7cicl/zswiyE33P
        4qB2rpcudpeuG2uJTiv2PG4hJngtHEi0UEybJSnInZEEOVVokN/5zhCzirGOp+k3
        7c1MZ3BocIfVQTtu2jKzBzSk2FkgJYiGEZSYmLehK2JJc/ECQQDQnYoL0JKefcgZ
        s1c8wLuEBrteCtmomiSCK8WHydjpMFOqC0+ysoHTqQBlCwLBIkKFfQJ6v2H+lXha
        6Nk70icpAkEA7IbLu9YHdK5gPggO4OjbEvl7NOzDSdGFOHjRE4GaEcicBsq3du9G
        sOvDWyVjhS7Nwy0jkW/oFFLb5jWfrONfdwJBAK8b/ftK2TemdydzjX+WfBAnonEf
        BHLs6EZHvafse2HJygCLPBvQkP989bLbGjXJrzLjqwgjy3rqNjuBBo+bKHkCQFUw
        J2i7qWvI8jjlRhaTR3QKDun87ElGASlZulPANfF5w1he4r0faOKHx5CoYrOxK8LE
        Gy9ikr/fJ/w+DAiEy/kCQQCgHW6qtsppmhSMFDFdXFBa0DQcpddkqY2BRMYl0vA3
        W+0VPF/w88+q8037SzqtPgwsaKfa4lALHlP84XWUYXDK
        -----END RSA PRIVATE KEY-----

  oniontree:
    image: oniontree:alpine-3.11-go1.13
    container_name: oniontree_web
    build:
      context: .
      dockerfile: Dockerfile
    networks:
    - onionltd
    ports:
    - 9000:9000
    #volumes:
    #- ./oniontree/tagged:/opt/oniontree/data/tagged
    #- ./oniontree/unsorted:/opt/oniontree/data/unsorted

networks:
  onionltd:
    external: false